"""The report data model.

Kept separate from rendering (:mod:`ath.reporting.markdown`) and assembly
(:mod:`ath.reporting.builder`) for the same reason the rest of the project separates
data from presentation: a typed :class:`Report` can be tested, diffed, and serialised to
JSON on its own, independent of whatever Markdown or HTML template happens to render it
today. If a second output format is ever wanted, this model does not change.

Every field here traces back to something the deterministic pipeline or the
investigation agent already produced. Nothing in this model is generated by prose --
the model holds structured content, and calibrated wording is applied only at render
time (see :mod:`ath.reporting.language`).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from ath.agent.claims import Claim
from ath.correlation.chain import TimelineEntry
from ath.hunting.finding import Severity
from ath.mitre.attack import AttackMapping


@dataclass(frozen=True)
class EvidenceAppendixEntry:
    """One raw telemetry event, rendered for the report's evidence appendix.

    The appendix exists so the report is self-contained: a reader should not have to
    re-run the tool suite to see what ``evt-000322`` actually was.

    Attributes:
        source: Which TelemetrySource produced this event (e.g. "synthetic" or
            "defender_export"). Carried through so a report is honest about whether it
            describes a demo scenario or a real, imported investigation.
    """

    event_id: str
    timestamp: datetime
    device: str
    user: str
    summary: str
    source: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "event_id": self.event_id,
            "timestamp": self.timestamp.isoformat(),
            "device": self.device,
            "user": self.user,
            "summary": self.summary,
            "source": self.source,
        }


@dataclass(frozen=True)
class RecommendedAction:
    """One recommended next step for a human analyst.

    Attributes:
        action: What to do, in plain language.
        rationale: Why -- tied to a specific claim or evidence gap, not generic advice.
        based_on: The claim statement (or gap) that motivated this recommendation, so
            the recommendation itself is traceable rather than templated filler.
    """

    action: str
    rationale: str
    based_on: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {"action": self.action, "rationale": self.rationale, "based_on": self.based_on}


VERDICT_LABELS: tuple[str, ...] = ("Malicious", "Benign", "Abstain", "Incomplete")
"""Every way a report's verdict can read. There is no fifth, and no numeric score."""


@dataclass(frozen=True)
class Verdict:
    """What the investigation concluded, and on what basis -- stated, never scored.

    This system produces no verdict confidence. A model's disposition is a label it
    chose; nothing downstream turns it into a probability, and this dataclass
    deliberately has no field where one could be put. What a reader gets instead is
    ``evidence_basis``: a count of what was actually checked.

    Attributes:
        disposition: One of :data:`VERDICT_LABELS`. ``"Incomplete"`` whenever the
            operational outcome was not complete or no disposition was produced.
        incomplete_reasons: Why the verdict is Incomplete, from the run's own recorded
            reasons and stop reason. Empty otherwise.
        model_disposition: The model's own last disposition before any operational
            downgrade (``None`` when no model concluded). Shown so an Incomplete
            verdict does not hide what the model provisionally said.
        evidence_gap: The model's own note on what evidence was missing (model text).
        supporting_event_ids: Event ids cited by the concluding explanations. Empty
            when the verdict is Incomplete: a provisional explanation supports nothing.
        verified_event_ids: The subset of ``supporting_event_ids`` naming events the
            investigation actually retrieved. This verifies the citation, not the
            meaning of the sentence that cited it.
        evidence_basis: A factual description of what was checked (counts only).
        engine, profile, model: What produced the result.
        disposition_source: Who decided the disposition: the model's concluding round,
            or, for the deterministic engine, rule-based triage of the seed findings.
            Empty when the verdict is Incomplete.
    """

    disposition: str
    incomplete_reasons: tuple[str, ...] = ()
    model_disposition: str | None = None
    evidence_gap: str = ""
    supporting_event_ids: tuple[str, ...] = ()
    verified_event_ids: tuple[str, ...] = ()
    evidence_basis: str = ""
    engine: str = ""
    profile: str = ""
    model: str = ""
    disposition_source: str = ""

    def __post_init__(self) -> None:
        if self.disposition not in VERDICT_LABELS:
            raise ValueError(f"verdict must be one of {VERDICT_LABELS}, not {self.disposition!r}")

    @property
    def complete(self) -> bool:
        return self.disposition != "Incomplete"

    def to_dict(self) -> dict[str, Any]:
        return {
            "disposition": self.disposition,
            "complete": self.complete,
            "incomplete_reasons": list(self.incomplete_reasons),
            "model_disposition": self.model_disposition,
            "evidence_gap": self.evidence_gap,
            "supporting_event_ids": list(self.supporting_event_ids),
            "verified_event_ids": list(self.verified_event_ids),
            "evidence_basis": self.evidence_basis,
            "engine": self.engine,
            "profile": self.profile,
            "model": self.model,
            "disposition_source": self.disposition_source,
        }


@dataclass(frozen=True)
class InvestigationStep:
    """One branch of the investigation tree: a model-chosen probe or a specialist step.

    Attributes:
        kind: ``"probe"`` (the model chose it), ``"refused_probe"`` (the model asked for
            something not on its menu; nothing ran) or ``"specialist"`` (the
            deterministic orchestrator ran it).
        name: Tool name for a probe, specialist name otherwise.
        arguments: The probe's arguments, summarised (``user='acct-7085'``).
        reason: Why it ran. Model-written for a probe; the plan log's own
            deterministic reason for a specialist -- ``reason_source`` says which.
        reason_source: ``"model"`` or ``"deterministic"``.
        tools: Tools a specialist step called, in order.
        new_event_ids: Event ids this step surfaced that were not in the seed.
        new_event_count: How many such ids the step retrieved in total (may exceed
            ``len(new_event_ids)`` when a result was cut before the model saw it).
    """

    kind: str
    name: str
    arguments: str = ""
    reason: str = ""
    reason_source: str = ""
    tools: tuple[str, ...] = ()
    new_event_ids: tuple[str, ...] = ()
    new_event_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind, "name": self.name, "arguments": self.arguments,
            "reason": self.reason, "reason_source": self.reason_source,
            "tools": list(self.tools), "new_event_ids": list(self.new_event_ids),
            "new_event_count": self.new_event_count,
        }


@dataclass(frozen=True)
class InvestigationTree:
    """Initial alert -> each step taken -> verdict, as recorded by the run.

    Attributes:
        alert_title: The case title (see :attr:`Report.title`).
        rule_ids: The detection rules whose findings formed the case.
        seed_event_ids: Every event the case's findings cite -- what the run started from.
        engine: ``"d1"`` (model-chosen probes) or ``"deterministic"`` (specialists).
        steps: The branches, in the order they ran.
        stop_reason: Why the investigation stopped, as the run recorded it.
    """

    alert_title: str
    rule_ids: tuple[str, ...]
    seed_event_ids: tuple[str, ...]
    engine: str
    steps: tuple[InvestigationStep, ...] = ()
    stop_reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "alert_title": self.alert_title, "rule_ids": list(self.rule_ids),
            "seed_event_ids": list(self.seed_event_ids), "engine": self.engine,
            "steps": [s.to_dict() for s in self.steps], "stop_reason": self.stop_reason,
        }


@dataclass(frozen=True)
class ModelExplanation:
    """One explanation from the model's concluding round -- model-written, not fact.

    Attributes:
        label: The model's label for the explanation (e.g. ``"malicious"``).
        statement: The model's own words, unedited.
        evidence_ids: Every id the model cited.
        verified_ids: Cited ids naming events the investigation actually retrieved.
            Any cited id not in this set was not shown to the model or does not exist.
        status: What the claim verifier did with it: ``"accepted"``,
            ``"rejected: <reason>"``, ``"provisional (investigation incomplete)"`` or
            ``"not recorded"``.
    """

    label: str
    statement: str
    evidence_ids: tuple[str, ...] = ()
    verified_ids: tuple[str, ...] = ()
    status: str = ""

    @property
    def unverified_ids(self) -> tuple[str, ...]:
        return tuple(e for e in self.evidence_ids if e not in self.verified_ids)

    def to_dict(self) -> dict[str, Any]:
        return {
            "label": self.label, "statement": self.statement,
            "evidence_ids": list(self.evidence_ids), "verified_ids": list(self.verified_ids),
            "status": self.status,
        }


@dataclass
class Report:
    """A complete, evidence-backed investigation report for one case.

    This is deliberately *not* a narrative document at the model level -- it is a
    structured object. Calibrated prose is produced only when rendering
    (:func:`ath.reporting.markdown.render_markdown`), which keeps the report auditable:
    every sentence in the rendered output can be traced back to one field here, and
    every field here traces back to a Claim, a Finding, or an AttackMapping.

    Attributes:
        case_id: The investigated case.
        generated_at: When this report was assembled (UTC).
        status: The investigation's terminal status (e.g. "complete").
        severity: The case's highest-severity finding.
        grouping_confidence: How strongly the correlator linked these findings
            ("low"/"medium"/"high") -- NOT a statement about whether an intrusion
            occurred, and the render layer must never conflate the two.
        devices, users: Scope of the case.
        start_time, end_time, duration_seconds: The case's observed time window.
        tactics: ATT&CK tactics in kill-chain order.
        timeline: Chronological, evidence-cited findings.
        facts, inferences, hypotheses: The investigation's claims, already verified.
        rejected_claim_count: How many claims the verifier discarded -- reported even
            when zero, so the absence of hallucination is visible, not assumed.
        mitre_mappings: Deduplicated technique interpretations across the case.
        agents_run: Which specialists executed.
        investigation_path: The orchestrator's own plan log -- why each step happened.
        tool_call_count: Total tool invocations behind this report.
        recommended_actions: Analyst next steps. Never destructive, never automatic.
        limitations: What this report does not and cannot establish.
        evidence_appendix: Every underlying telemetry event, in order.
    """

    case_id: str
    generated_at: datetime
    status: str
    severity: Severity
    grouping_confidence: str
    devices: tuple[str, ...]
    users: tuple[str, ...]
    start_time: datetime
    end_time: datetime
    duration_seconds: int
    tactics: tuple[str, ...]
    timeline: tuple[TimelineEntry, ...]
    facts: tuple[Claim, ...]
    inferences: tuple[Claim, ...]
    hypotheses: tuple[Claim, ...]
    rejected_claim_count: int
    mitre_mappings: tuple[AttackMapping, ...]
    agents_run: tuple[str, ...]
    investigation_path: tuple[str, ...]
    tool_call_count: int
    recommended_actions: tuple[RecommendedAction, ...]
    limitations: tuple[str, ...]
    evidence_appendix: tuple[EvidenceAppendixEntry, ...]
    executive_summary: str = ""
    evidence_verification: dict[str, Any] = field(default_factory=dict)
    data_sources: tuple[str, ...] = ()
    """Distinct TelemetrySource names underlying this report's evidence (e.g.
    ("synthetic",) for a demo scenario, ("defender_export",) for a real import).
    Never hardcoded -- derived from the evidence appendix's own `source` field, so it
    cannot drift out of sync with what the report actually describes."""
    title: str = ""
    """The case title, from its findings' own titles (see ``Incident:`` in the render)."""
    verdict: Verdict | None = None
    """What the run concluded. Always set by :func:`~ath.reporting.build_report`."""
    investigation_tree: InvestigationTree | None = None
    """Initial alert -> steps -> verdict. Always set by ``build_report``."""
    reasoning_summary: tuple[ModelExplanation, ...] = ()
    """The model's concluding explanations, verbatim. Empty for deterministic runs."""
    elapsed_seconds: float | None = None
    """Wall-clock run time, when the operational audit recorded it."""

    @property
    def all_claims(self) -> tuple[Claim, ...]:
        return self.facts + self.inferences + self.hypotheses

    @property
    def claim_count(self) -> int:
        return len(self.all_claims)

    @property
    def unique_event_ids(self) -> tuple[str, ...]:
        return tuple(sorted({e.event_id for e in self.evidence_appendix}))

    def to_dict(self) -> dict[str, Any]:
        return {
            "case_id": self.case_id,
            **({"evidence_verification": self.evidence_verification} if self.evidence_verification else {}),
            "generated_at": self.generated_at.isoformat(),
            "status": self.status,
            "severity": self.severity.value,
            "grouping_confidence": self.grouping_confidence,
            "devices": list(self.devices),
            "users": list(self.users),
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat(),
            "duration_seconds": self.duration_seconds,
            "tactics": list(self.tactics),
            "timeline": [t.to_dict() for t in self.timeline],
            "executive_summary": self.executive_summary,
            "facts": [c.to_dict() for c in self.facts],
            "inferences": [c.to_dict() for c in self.inferences],
            "hypotheses": [c.to_dict() for c in self.hypotheses],
            "rejected_claim_count": self.rejected_claim_count,
            "mitre_mappings": [m.to_dict() for m in self.mitre_mappings],
            "agents_run": list(self.agents_run),
            "investigation_path": list(self.investigation_path),
            "tool_call_count": self.tool_call_count,
            "recommended_actions": [a.to_dict() for a in self.recommended_actions],
            "limitations": list(self.limitations),
            "evidence_appendix": [e.to_dict() for e in self.evidence_appendix],
            "data_sources": list(self.data_sources),
            "title": self.title,
            "verdict": self.verdict.to_dict() if self.verdict else None,
            "investigation_tree": (
                self.investigation_tree.to_dict() if self.investigation_tree else None
            ),
            "reasoning_summary": [e.to_dict() for e in self.reasoning_summary],
            "elapsed_seconds": self.elapsed_seconds,
        }
