"""The report data model.

Kept separate from rendering (:mod:`ath.reporting.markdown`) and assembly
(:mod:`ath.reporting.builder`) for the same reason the rest of the project separates
data from presentation: a typed :class:`Report` can be tested, diffed, and serialised to
JSON on its own, independent of whatever Markdown or HTML template happens to render it
today. If a second output format is ever wanted, this model does not change.

Every field here traces back to something the deterministic pipeline or the
investigation agent already produced. Nothing in this model is generated by prose --
the model holds structured content, and calibrated wording is applied only at render
time (see :mod:`ath.reporting.language`).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any

from ath.agent.claims import Claim
from ath.correlation.chain import TimelineEntry
from ath.hunting.finding import Severity
from ath.mitre.attack import AttackMapping


@dataclass(frozen=True)
class EvidenceAppendixEntry:
    """One raw telemetry event, rendered for the report's evidence appendix.

    The appendix exists so the report is self-contained: a reader should not have to
    re-run the tool suite to see what ``evt-000322`` actually was.

    Attributes:
        source: Which TelemetrySource produced this event (e.g. "synthetic" or
            "defender_export"). Carried through so a report is honest about whether it
            describes a demo scenario or a real, imported investigation.
    """

    event_id: str
    timestamp: datetime
    device: str
    user: str
    summary: str
    source: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "event_id": self.event_id,
            "timestamp": self.timestamp.isoformat(),
            "device": self.device,
            "user": self.user,
            "summary": self.summary,
            "source": self.source,
        }


@dataclass(frozen=True)
class RecommendedAction:
    """One recommended next step for a human analyst.

    Attributes:
        action: What to do, in plain language.
        rationale: Why -- tied to a specific claim or evidence gap, not generic advice.
        based_on: The claim statement (or gap) that motivated this recommendation, so
            the recommendation itself is traceable rather than templated filler.
    """

    action: str
    rationale: str
    based_on: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {"action": self.action, "rationale": self.rationale, "based_on": self.based_on}


@dataclass
class Report:
    """A complete, evidence-backed investigation report for one case.

    This is deliberately *not* a narrative document at the model level -- it is a
    structured object. Calibrated prose is produced only when rendering
    (:func:`ath.reporting.markdown.render_markdown`), which keeps the report auditable:
    every sentence in the rendered output can be traced back to one field here, and
    every field here traces back to a Claim, a Finding, or an AttackMapping.

    Attributes:
        case_id: The investigated case.
        generated_at: When this report was assembled (UTC).
        status: The investigation's terminal status (e.g. "complete").
        severity: The case's highest-severity finding.
        grouping_confidence: How strongly the correlator linked these findings
            ("low"/"medium"/"high") -- NOT a statement about whether an intrusion
            occurred, and the render layer must never conflate the two.
        devices, users: Scope of the case.
        start_time, end_time, duration_seconds: The case's observed time window.
        tactics: ATT&CK tactics in kill-chain order.
        timeline: Chronological, evidence-cited findings.
        facts, inferences, hypotheses: The investigation's claims, already verified.
        rejected_claim_count: How many claims the verifier discarded -- reported even
            when zero, so the absence of hallucination is visible, not assumed.
        mitre_mappings: Deduplicated technique interpretations across the case.
        agents_run: Which specialists executed.
        investigation_path: The orchestrator's own plan log -- why each step happened.
        tool_call_count: Total tool invocations behind this report.
        recommended_actions: Analyst next steps. Never destructive, never automatic.
        limitations: What this report does not and cannot establish.
        evidence_appendix: Every underlying telemetry event, in order.
    """

    case_id: str
    generated_at: datetime
    status: str
    severity: Severity
    grouping_confidence: str
    devices: tuple[str, ...]
    users: tuple[str, ...]
    start_time: datetime
    end_time: datetime
    duration_seconds: int
    tactics: tuple[str, ...]
    timeline: tuple[TimelineEntry, ...]
    facts: tuple[Claim, ...]
    inferences: tuple[Claim, ...]
    hypotheses: tuple[Claim, ...]
    rejected_claim_count: int
    mitre_mappings: tuple[AttackMapping, ...]
    agents_run: tuple[str, ...]
    investigation_path: tuple[str, ...]
    tool_call_count: int
    recommended_actions: tuple[RecommendedAction, ...]
    limitations: tuple[str, ...]
    evidence_appendix: tuple[EvidenceAppendixEntry, ...]
    executive_summary: str = ""
    data_sources: tuple[str, ...] = ()
    """Distinct TelemetrySource names underlying this report's evidence (e.g.
    ("synthetic",) for a demo scenario, ("defender_export",) for a real import).
    Never hardcoded -- derived from the evidence appendix's own `source` field, so it
    cannot drift out of sync with what the report actually describes."""

    @property
    def all_claims(self) -> tuple[Claim, ...]:
        return self.facts + self.inferences + self.hypotheses

    @property
    def claim_count(self) -> int:
        return len(self.all_claims)

    @property
    def unique_event_ids(self) -> tuple[str, ...]:
        return tuple(sorted({e.event_id for e in self.evidence_appendix}))

    def to_dict(self) -> dict[str, Any]:
        return {
            "case_id": self.case_id,
            "generated_at": self.generated_at.isoformat(),
            "status": self.status,
            "severity": self.severity.value,
            "grouping_confidence": self.grouping_confidence,
            "devices": list(self.devices),
            "users": list(self.users),
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat(),
            "duration_seconds": self.duration_seconds,
            "tactics": list(self.tactics),
            "timeline": [t.to_dict() for t in self.timeline],
            "executive_summary": self.executive_summary,
            "facts": [c.to_dict() for c in self.facts],
            "inferences": [c.to_dict() for c in self.inferences],
            "hypotheses": [c.to_dict() for c in self.hypotheses],
            "rejected_claim_count": self.rejected_claim_count,
            "mitre_mappings": [m.to_dict() for m in self.mitre_mappings],
            "agents_run": list(self.agents_run),
            "investigation_path": list(self.investigation_path),
            "tool_call_count": self.tool_call_count,
            "recommended_actions": [a.to_dict() for a in self.recommended_actions],
            "limitations": list(self.limitations),
            "evidence_appendix": [e.to_dict() for e in self.evidence_appendix],
            "data_sources": list(self.data_sources),
        }
