"""M20 provenance: assemble the manifest entry the plan's section 7 proposes.

What section 3 requires
------------------------
"**Provenance recorded:** account id (redacted to last 4), region list, trail ARN, the
``sessions.csv`` with both planned and actual times, the exact scripts/Terraform used,
the IAM policies attached to each role at each point in time, sha256 of every delivered
CloudTrail ``.json.gz``, and the operator's own attestation that no adversarial action
was taken."

Each of those is a required input here, and the entry cannot be assembled without it
(INV-3). That is the point: a provenance record whose fields are optional is a record of
whatever the operator happened to remember.

Shape
------
The output plugs into ``data/external/MANIFEST.json`` unchanged. That file is
``{_about, datasets, _attack_generation}`` and ``scripts/fetch_external.py`` reads
``datasets[name]["files"]`` as ``{path, bytes, sha256}`` triples rooted at
``data/external/``, so the entry is written under ``datasets["m20_benign_cloud"]`` with
exactly that ``files`` shape -- ``--verify-only`` then checks this corpus the same way it
checks the four third-party ones.

The plan's own prose about this entry is kept verbatim in ``license``, ``provenance``,
``telemetry``, ``subset_kept`` and ``labels``: those five values are the claim being
made about the corpus, and re-wording them here is how a claim drifts.

Two guards worth naming
------------------------
*The account id never appears.* Only the last four digits are recorded, and
:func:`refuse_account_id_leak` scans the assembled entry for the full id before it is
printed or written -- including inside ``fetch_command``, which is where it would
otherwise survive as part of a bucket name.

*The holdout is still not opened.* File facts come from ``SPLIT.json`` when it exists,
and otherwise from hashing bytes. Nothing decompresses anything (INV-1).

Usage::

    python scripts/m20/provenance.py \
        --split-dir data/external/m20_benign_cloud \
        --sessions reports/m20/sessions.csv \
        --account-id 012345678901 --regions us-east-1,eu-west-1 \
        --trail-arn arn:aws:cloudtrail:us-east-1:012345678901:trail/ath-m20-baseline \
        --iam-policies-dir reports/m20/iam_snapshots \
        --attestation-file reports/m20/ATTESTATION.txt \
        --fetched-on 2026-10-15 --write --manifest data/external/MANIFEST.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
DATASET_KEY = "m20_benign_cloud"
DEFAULT_MANIFEST = ROOT / "data" / "external" / "MANIFEST.json"
DEFAULT_SCRIPTS_DIR = ROOT / "scripts" / "m20"

SPLIT_RECORD = "SPLIT.json"
SIDES = ("dev", "holdout")

#: Section 7's proposed values, verbatim. Reflowed only for line length.
ENTRY_TEXT = {
    "name": "ATH M20 benign cloud baseline (disposable AWS account, 14 days)",
    "publisher": "this project (own data)",
    "source_page": "docs/m20-benign-cloud-validation-plan.md",
    "license": (
        "Own data. Generated by this project in a disposable account created for the "
        "purpose. Redistributable once account identifiers are redacted."
    ),
    "provenance": (
        "real -- real AWS CloudTrail from real API calls; benign by construction, every "
        "session predeclared in sessions.csv before it ran"
    ),
    "telemetry": (
        "AWS CloudTrail management events (read+write, all regions, global service "
        "events), {Records:[...]} JSON, gzipped, S3 delivery layout"
    ),
    "subset_kept": (
        "whole trail; split by calendar date -- days 1-9 dev, days 10-14 sealed"
    ),
    "labels": (
        "every event is benign by construction; sessions.csv gives actor, workflow id "
        "and start/end for each session, written before execution"
    ),
}

FETCH_COMMAND = (
    "aws s3 sync s3://ath-m20-trail-<acct>/AWSLogs/ data/external/m20_benign_cloud/"
)


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_of_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def directory_digest(directory: Path, skip_suffixes=(".pyc",)) -> dict:
    """A deterministic hash of a directory's contents, plus the file list it covers.

    "the exact scripts/Terraform used" is not answerable by a path -- the path is the
    same before and after somebody edits a workflow mid-collection. The digest is taken
    over sorted ``relative path + NUL + sha256`` lines so it is stable across platforms
    and independent of mtimes, and the per-file list is kept so a later mismatch can be
    localised rather than merely detected.
    """
    if not directory.is_dir():
        raise SystemExit("{0} is not a directory".format(directory))
    files = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix in skip_suffixes or "__pycache__" in path.parts:
            continue
        relative = path.relative_to(directory).as_posix()
        files.append({"path": relative, "sha256": sha256_of(path), "bytes": path.stat().st_size})
    lines = "".join("{0}\0{1}\n".format(entry["path"], entry["sha256"]) for entry in files)
    return {
        "directory": directory.as_posix(),
        "files": files,
        "sha256": sha256_of_text(lines),
        "method": "sha256 over sorted '<relative path>\\0<file sha256>\\n' lines",
    }


def split_files(split_dir: Path, dataset_prefix: str) -> list:
    """Every delivered file, as ``{path, bytes, sha256}`` rooted at ``data/external/``.

    Prefers ``SPLIT.json`` -- written by ``split.py`` at sealing time, from the same
    bytes -- so that assembling provenance does not re-touch the holdout at all. Falls
    back to hashing the files in place, which is still bytes-only.

    Raises:
        SystemExit: if neither a split record nor a ``dev``/``holdout`` layout exists.
    """
    record_path = split_dir / SPLIT_RECORD
    entries = []
    if record_path.exists():
        record = json.loads(record_path.read_text(encoding="utf-8"))
        for side in SIDES:
            for item in record.get(side, []):
                entries.append({
                    "path": "{0}/{1}/{2}".format(dataset_prefix, side, item["name"]),
                    "bytes": item["bytes"],
                    "sha256": item["sha256"],
                })
        if entries:
            return entries

    found_any_side = False
    for side in SIDES:
        side_dir = split_dir / side
        if not side_dir.is_dir():
            continue
        found_any_side = True
        for path in sorted(side_dir.glob("*.json.gz")):
            entries.append({
                "path": "{0}/{1}/{2}".format(dataset_prefix, side, path.name),
                "bytes": path.stat().st_size,
                "sha256": sha256_of(path),
            })
    if not found_any_side:
        raise SystemExit(
            "{0} holds neither {1} nor dev/ and holdout/ directories. Run split.py "
            "first.".format(split_dir, SPLIT_RECORD)
        )
    return entries


def account_id_in_file_names(entry: dict, account_id: str) -> bool:
    """Whether the delivered file names carry the full account id. They will.

    CloudTrail names every delivered object ``<account>_CloudTrail_<region>_...``, so the
    account id is *in the data's own file names*, and ``files[]`` has to quote them
    verbatim or ``scripts/fetch_external.py`` could not find the files it verifies.
    Rewriting the paths would make the manifest disagree with the disk; renaming the
    files would invalidate the sealing hashes taken at split time.

    So this is measured and recorded rather than refused, and the entry says so: the
    plan's own licence text ("Redistributable once account identifiers are redacted")
    then names a step that must happen before redistribution, not before writing the
    manifest.
    """
    if len(account_id) != 12 or not account_id.isdigit():
        return False
    return any(account_id in spec["path"] for spec in entry.get("files", []))


def refuse_account_id_leak(entry: dict, account_id: str) -> None:
    """Refuse to emit an entry whose *operator-written* fields carry the full account id.

    The plan redacts the account to its last four digits. A 12-digit id pasted into the
    trail ARN, or surviving in a bucket name inside ``fetch_command``, would undo that
    silently -- and the manifest is the file most likely to be shown to somebody outside
    the project.

    The delivered file names are the one exception, and they are excluded here rather
    than tolerated silently: see :func:`account_id_in_file_names`, whose answer the entry
    records.

    Raises:
        SystemExit: naming the leak, so the operator can redact rather than guess.
    """
    if len(account_id) != 12 or not account_id.isdigit():
        return
    scanned = {key: value for key, value in entry.items() if key != "files"}
    scanned["collection_provenance"] = {
        key: value for key, value in entry["collection_provenance"].items()
        if key not in ("delivered_files",)
    }
    if account_id in json.dumps(scanned):
        raise SystemExit(
            "the full account id {0} appears in the assembled entry. Section 3 redacts "
            "it to the last four digits; redact the field that carries it (usually the "
            "trail ARN or a bucket name) before writing the manifest. The delivered "
            "file names are exempt -- CloudTrail puts the account id in every object "
            "key, and the entry records that fact.".format(account_id)
        )


def build_entry(
    split_dir: Path,
    sessions_csv: Path,
    account_id: str,
    regions: list,
    trail_arn: str,
    iam_policies_dir: Path,
    attestation: str,
    scripts_dir: Path,
    fetched_on: str,
    dataset_prefix: str = DATASET_KEY,
) -> dict:
    """Assemble the section 7 entry plus the section 3 provenance block (INV-3)."""
    if not sessions_csv.exists():
        raise SystemExit(
            "{0} does not exist. The manifest entry claims every session was predeclared; "
            "without sessions.csv that claim has no evidence.".format(sessions_csv)
        )
    if not attestation.strip():
        raise SystemExit(
            "the attestation file is empty. Section 3 requires \"the operator's own "
            "attestation that no adversarial action was taken\" -- an empty one is a "
            "missing one."
        )

    files = split_files(split_dir, dataset_prefix)
    sessions_entry = {
        "path": "{0}/sessions.csv".format(dataset_prefix),
        "bytes": sessions_csv.stat().st_size,
        "sha256": sha256_of(sessions_csv),
        "repo_path": sessions_csv.as_posix(),
    }

    entry = {
        "name": ENTRY_TEXT["name"],
        "publisher": ENTRY_TEXT["publisher"],
        "url": None,
        "source_page": ENTRY_TEXT["source_page"],
        "license": ENTRY_TEXT["license"],
        "provenance": ENTRY_TEXT["provenance"],
        "telemetry": ENTRY_TEXT["telemetry"],
        "files": files + [sessions_entry],
        "fetched_on": fetched_on,
        "fetch_command": FETCH_COMMAND,
        "subset_kept": ENTRY_TEXT["subset_kept"],
        "labels": ENTRY_TEXT["labels"],
        # Everything below is what section 3 lists under "Provenance recorded" and the
        # existing entries have no equivalent of, because they are third-party fetches
        # and this is the first corpus the project produced itself.
        "collection_provenance": {
            "_about": (
                "docs/m20-benign-cloud-validation-plan.md section 3, \"Provenance "
                "recorded\". Assembled by scripts/m20/provenance.py."
            ),
            "account_id_last4": account_id[-4:],
            "regions": regions,
            "trail_arn": trail_arn,
            "sessions_csv": sessions_entry,
            "scripts": directory_digest(scripts_dir),
            "iam_policy_snapshots": directory_digest(iam_policies_dir),
            "delivered_files": {
                "count": len(files),
                "dev": sum(1 for f in files if "/dev/" in f["path"]),
                "holdout": sum(1 for f in files if "/holdout/" in f["path"]),
                "bytes": sum(f["bytes"] for f in files),
                "note": (
                    "holdout hashes were taken over bytes at sealing time; no holdout "
                    "file has been decompressed or parsed"
                ),
            },
            "account_id_in_delivered_file_names": None,  # filled below, once files[] exists
            "operator_attestation": attestation.strip(),
            "assembled_on": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        },
    }
    entry["collection_provenance"]["account_id_in_delivered_file_names"] = {
        "value": account_id_in_file_names(entry, account_id),
        "why": (
            "CloudTrail names every delivered object <account>_CloudTrail_<region>_..., "
            "and files[] must quote the names on disk for fetch_external.py to verify "
            "them. The licence's \"redistributable once account identifiers are "
            "redacted\" therefore requires renaming these files (and re-hashing them) "
            "before the corpus leaves the project."
        ),
    }
    refuse_account_id_leak(entry, account_id)
    return entry


def merge_into_manifest(manifest_path: Path, entry: dict, force: bool = False) -> dict:
    """Merge the entry under ``datasets["m20_benign_cloud"]``.

    A manifest that does not exist is created with the same ``{_about, datasets}`` shape
    ``fetch_external.py`` expects, rather than failing: this worktree may not carry
    ``data/external/MANIFEST.json`` at all, and the operator is not helped by being told
    to hand-write a skeleton.

    Raises:
        SystemExit: if an entry already exists and ``force`` is not set. Overwriting a
            provenance record in place is how the hash of "the exact scripts used"
            quietly becomes the hash of the scripts as they are now.
    """
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    else:
        manifest = {
            "_about": (
                "External datasets used by this project. Each entry records what was "
                "fetched, from where, under what licence, and the sha256 of every file."
            ),
            "datasets": {},
        }
    datasets = manifest.setdefault("datasets", {})
    if DATASET_KEY in datasets and not force:
        raise SystemExit(
            "{0} already holds datasets[{1!r}]. Pass --force to replace it, and say in "
            "the report why the recorded provenance changed.".format(manifest_path, DATASET_KEY)
        )
    datasets[DATASET_KEY] = entry
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--split-dir", type=Path, required=True,
                        help="directory holding dev/, holdout/ and SPLIT.json")
    parser.add_argument("--sessions", type=Path, required=True, help="reports/m20/sessions.csv")
    parser.add_argument("--account-id", required=True, help="12-digit account id; only the last 4 are recorded")
    parser.add_argument("--regions", required=True, help="comma-separated region list")
    parser.add_argument("--trail-arn", required=True)
    parser.add_argument("--iam-policies-dir", type=Path, required=True,
                        help="directory of IAM policy snapshots, one per role per change")
    parser.add_argument("--attestation-file", type=Path, required=True,
                        help="operator attestation that no adversarial action was taken")
    parser.add_argument("--scripts-dir", type=Path, default=DEFAULT_SCRIPTS_DIR)
    parser.add_argument("--fetched-on", default=datetime.utcnow().strftime("%Y-%m-%d"))
    parser.add_argument("--dataset-prefix", default=DATASET_KEY,
                        help="path prefix used inside data/external/ for files[]")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--write", action="store_true", help="merge the entry into --manifest")
    parser.add_argument("--force", action="store_true", help="replace an existing entry")
    args = parser.parse_args(argv)

    if not args.attestation_file.exists():
        raise SystemExit("{0} does not exist".format(args.attestation_file))

    entry = build_entry(
        split_dir=args.split_dir,
        sessions_csv=args.sessions,
        account_id=args.account_id,
        regions=[r.strip() for r in args.regions.split(",") if r.strip()],
        trail_arn=args.trail_arn,
        iam_policies_dir=args.iam_policies_dir,
        attestation=args.attestation_file.read_text(encoding="utf-8"),
        scripts_dir=args.scripts_dir,
        fetched_on=args.fetched_on,
        dataset_prefix=args.dataset_prefix,
    )
    print(json.dumps({DATASET_KEY: entry}, indent=2))
    if args.write:
        merge_into_manifest(args.manifest, entry, force=args.force)
        print("\nmerged into {0} under datasets[{1!r}]".format(args.manifest, DATASET_KEY),
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
