"""M19b T4: audit every corpus and case this repository can build for cross-specialist
necessity, and write ``reports/m19b/necessity/AUDIT.{md,json}``.

What this script does and does not do
--------------------------------------
It **loads** every corpus through the same adapters the pipeline uses, **hunts**,
**triages** and **correlates** exactly as ``scripts/m19_ablation.py`` does, and then
runs arm A's deterministic investigation on every case so the eligibility it reports is
the eligibility the orchestrator actually produced. It changes no rule, no threshold and
no fixture, calls no model, and writes nothing outside ``reports/m19b/necessity/``.

Where the data lives
---------------------
``data/external/`` is gitignored and exists only in the primary checkout, so this script
takes ``--external`` and defaults to a sibling checkout's copy. A corpus whose files are
not present is recorded as ``UNAVAILABLE`` with the path that was missing -- never
silently omitted, because "this corpus has no cross-domain cases" and "this corpus was
not loaded" are the two answers it would be most damaging to confuse.

Usage::

    python scripts/m19b_necessity_audit.py --corpora fast
    python scripts/m19b_necessity_audit.py            # every corpus, DEDALE included
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from collections import Counter
from collections.abc import Iterable, Iterator, Sequence
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from ath.correlation import correlate  # noqa: E402
from ath.environment import build_environment_model  # noqa: E402
from ath.evaluation.necessity import (  # noqa: E402
    CaseAudit,
    CorpusAudit,
    audit_case,
    audit_digest,
    event_id_index,
)
from ath.evaluation.suite import standard_suite  # noqa: E402
from ath.hunting import HuntConfig, run_hunt  # noqa: E402
from ath.schema import (  # noqa: E402
    EVENT_CONTROL,
    EVENT_LOGON,
    EVENT_NETWORK,
    EVENT_PROCESS,
)
from ath.telemetry.loader import Telemetry  # noqa: E402
from ath.triage import assess_findings, set_aside_ids  # noqa: E402
from pre_schema_parquet import read_canonical_table  # noqa: E402

OUT_DIR = ROOT / "reports" / "m19b" / "necessity"
DEFAULT_EXTERNAL = ROOT.parent / "agentic-threat-hunter" / "data" / "external"

# Provenance vocabulary, fixed by the plan. A corpus gets exactly one of these, and the
# label is about how the *attack* in it came to exist, not about how the file was made:
# real benign traffic with a hand-written intrusion dropped into it is not real data
# about an intrusion, however real the background is.
REAL_LABELLED = "real labelled multi-domain"
REAL_UNLABELLED = "real, unlabelled (no attack ground truth)"
REAL_BENIGN = "real benign, no attack present"
EMULATION = "realistic emulation (labelled testbed attack)"
SYNTHETIC = "synthetic (generated by this repository)"
REAL_SHAPED = "real-shaped fixture (hand-cut from real data, committed)"


# --------------------------------------------------------------------------------------
# Corpus definitions
# --------------------------------------------------------------------------------------


def _telemetry_of(tables: dict[str, Any]) -> Telemetry:
    """Canonical telemetry from an adapter's tables, tolerating the ones it omits.

    ``DefenderExportSource`` returns no ``control`` table at all -- Defender has no
    control plane to export -- and indexing for one turned a corpus with three
    populated tables into a ``LOAD FAILED`` row. Absent tables become schema-valid
    empty frames, which is the same thing every other adapter already does for a table
    its source does not carry.
    """
    import pandas as pd  # noqa: PLC0415

    from ath.schema import TABLE_COLUMNS  # noqa: PLC0415

    def table(event_type: str) -> Any:
        frame = tables.get(event_type)
        if frame is None:
            return pd.DataFrame(columns=list(TABLE_COLUMNS[event_type]))
        return frame

    return Telemetry(
        processes=table(EVENT_PROCESS), network=table(EVENT_NETWORK),
        logons=table(EVENT_LOGON), controls=table(EVENT_CONTROL),
    )


def _cloudtrail(directory: Path) -> Telemetry:
    from ath.telemetry.cloudtrail_source import CloudTrailSource

    return _telemetry_of(CloudTrailSource(directory).load().tables)


def _k8s(directory: Path, cluster: str) -> Telemetry:
    from ath.telemetry.k8s_audit_source import K8sAuditSource

    return _telemetry_of(K8sAuditSource(directory, cluster=cluster).load().tables)


def _winlogbeat(directory: Path) -> Telemetry:
    from ath.telemetry.winlogbeat_source import WinlogbeatSource

    return _telemetry_of(WinlogbeatSource(directory).load().tables)


def _defender(directory: Path) -> Telemetry:
    from ath.telemetry.defender_source import DefenderExportSource

    return _telemetry_of(DefenderExportSource(directory).load().tables)


def _comiset() -> Telemetry:
    """The M18b canonical freeze -- the same bytes M19 investigated."""
    directory = ROOT / "reports" / "m18b" / "canonical"
    return Telemetry(
        processes=read_canonical_table(directory, "comiset", "process", EVENT_PROCESS),
        network=read_canonical_table(directory, "comiset", "network", EVENT_NETWORK),
        logons=read_canonical_table(directory, "comiset", "logon", EVENT_LOGON),
        controls=read_canonical_table(directory, "comiset", "control", EVENT_CONTROL),
    )


def _comiset_m17() -> Telemetry:
    """The M17 freeze: the same corpus before M18b added a control table.

    Audited beside the M18b freeze rather than instead of it, because the difference
    between them is the whole question this milestone asks -- whether adding a second
    domain's rows to a corpus changes what the crew can do with it.
    """
    directory = ROOT / "reports" / "m17" / "canonical"
    # ``read_canonical_table`` returns a schema-valid empty frame for a table the freeze
    # does not carry, which is exactly what the M17 freeze's missing control table is.
    return Telemetry(
        processes=read_canonical_table(directory, "comiset", "process", EVENT_PROCESS),
        network=read_canonical_table(directory, "comiset", "network", EVENT_NETWORK),
        logons=read_canonical_table(directory, "comiset", "logon", EVENT_LOGON),
        controls=read_canonical_table(directory, "comiset", "control", EVENT_CONTROL),
    )


def corpus_specs(external: Path) -> list[dict[str, Any]]:
    """Every corpus ATH can load today, with where it comes from and what it is.

    ``group`` splits the fast corpora from the ones that read hundreds of megabytes of
    Winlogbeat NDJSON, so the audit can be re-run cheaply while it is being written and
    completely before it is committed.
    """
    fixtures = ROOT / "tests" / "fixtures"
    return [
        {
            "name": "attack_data_aws", "group": "fast",
            "provenance": REAL_LABELLED,
            "source": str(external / "attack_data_aws" / "raw"),
            "load": lambda: _cloudtrail(external / "attack_data_aws" / "raw"),
            "path": external / "attack_data_aws" / "raw",
            "notes": (
                "Splunk attack_data: five single-technique CloudTrail captures. Each "
                "capture is one ATT&CK technique executed against a real AWS account, "
                "so the label is real and the attack is emulated. CloudTrail only: no "
                "process, no network flow."
            ),
        },
        {
            "name": "comiset", "group": "fast",
            "provenance": REAL_LABELLED,
            "source": str(ROOT / "reports" / "m18b" / "canonical"),
            "load": _comiset,
            "path": ROOT / "reports" / "m18b" / "canonical",
            "notes": (
                "COMISET, read from the M18b canonical freeze -- the same bytes M19 "
                "investigated. Windows endpoint + network + logon telemetry from a "
                "real enterprise environment."
            ),
        },
        {
            "name": "comiset_m17_freeze", "group": "fast",
            "provenance": REAL_LABELLED,
            "source": str(ROOT / "reports" / "m17" / "canonical"),
            "load": _comiset_m17,
            "path": ROOT / "reports" / "m17" / "canonical",
            "notes": (
                "The M17 freeze of the same corpus, audited to show whether the "
                "M18b widening changed which specialists a case reaches."
            ),
        },
        {
            "name": "flaws_cloud", "group": "fast",
            "provenance": REAL_UNLABELLED,
            "source": str(external / "flaws_cloud" / "raw"),
            "load": lambda: _cloudtrail(external / "flaws_cloud" / "raw"),
            "path": external / "flaws_cloud" / "raw",
            "notes": (
                "flaws.cloud: 1.9M real CloudTrail events from a deliberately "
                "vulnerable AWS account played with by the public for three years. "
                "Real attacker behaviour, and no labels at all -- the narrative on the "
                "site names no event ids."
            ),
        },
        {
            "name": "k8s_ci", "group": "fast",
            "provenance": REAL_BENIGN,
            "source": str(external / "k8s_ci" / "raw"),
            "load": lambda: _k8s(external / "k8s_ci" / "raw", "ci"),
            "path": external / "k8s_ci" / "raw",
            "notes": "Real kube-apiserver audit log from a CI cluster. Benign only.",
        },
        {
            "name": "k8ntext", "group": "fast",
            "provenance": EMULATION,
            "source": str(external / "k8ntext" / "raw"),
            "load": lambda: _k8s(external / "k8ntext" / "raw", "k8ntext"),
            "path": external / "k8ntext" / "raw",
            "notes": (
                "k8ntext: a real kubeadm cluster driven by a human administrator. "
                "Context ids, no attack labels; benign by construction."
            ),
        },
        {
            "name": "k8s_ingress", "group": "fast",
            "provenance": REAL_BENIGN,
            "source": str(external / "k8s_ingress" / "raw"),
            "load": lambda: _k8s(external / "k8s_ingress" / "raw", "ingress"),
            "path": external / "k8s_ingress" / "raw",
            "notes": "A second real kube-apiserver audit log. Benign only.",
        },
        {
            "name": "fixture:cloudtrail", "group": "fast",
            "provenance": SYNTHETIC,
            "source": str(fixtures / "cloudtrail"),
            "load": lambda: _cloudtrail(fixtures / "cloudtrail"),
            "path": fixtures / "cloudtrail",
            "notes": "INC-002's telemetry: a hand-written CloudTrail fixture.",
        },
        {
            "name": "fixture:k8s_audit", "group": "fast",
            "provenance": SYNTHETIC,
            "source": str(fixtures / "k8s_audit"),
            "load": lambda: _k8s(fixtures / "k8s_audit", "test-cluster"),
            "path": fixtures / "k8s_audit",
            "notes": "INC-005's telemetry: a hand-written Kubernetes audit fixture.",
        },
        {
            "name": "fixture:defender_export", "group": "fast",
            "provenance": SYNTHETIC,
            "source": str(fixtures / "defender_export"),
            "load": lambda: _defender(fixtures / "defender_export"),
            "path": fixtures / "defender_export",
            "notes": (
                "A hand-written Microsoft Defender advanced-hunting export: the only "
                "fixture in the repository carrying process, network and logon rows at "
                "once."
            ),
        },
        {
            "name": "fixture:real_shaped/dedale", "group": "fast",
            "provenance": REAL_SHAPED,
            "source": str(fixtures / "real_shaped" / "dedale"),
            "load": lambda: _winlogbeat(fixtures / "real_shaped" / "dedale"),
            "path": fixtures / "real_shaped" / "dedale",
            "notes": (
                "A committed slice of DEDALE Winlogbeat NDJSON (CLIENT2, 2024-12-25 "
                "boot hour). Real bytes, benign hour."
            ),
        },
        {
            "name": "fixture:real_shaped/k8s_ci", "group": "fast",
            "provenance": REAL_SHAPED,
            "source": str(fixtures / "real_shaped" / "k8s_ci"),
            "load": lambda: _k8s(fixtures / "real_shaped" / "k8s_ci", "ci"),
            "path": fixtures / "real_shaped" / "k8s_ci",
            "notes": "A committed slice of the real CI kube-apiserver audit log.",
        },
        {
            "name": "fixture:real_shaped/cloudtrail_shaped", "group": "fast",
            "provenance": REAL_SHAPED,
            "source": str(fixtures / "real_shaped" / "cloudtrail_shaped"),
            "load": lambda: _cloudtrail(fixtures / "real_shaped" / "cloudtrail_shaped"),
            "path": fixtures / "real_shaped" / "cloudtrail_shaped",
            "notes": "A committed tar slice of real flaws.cloud CloudTrail records.",
        },
        {
            "name": "dedale:D02", "group": "dedale", "provenance": EMULATION,
            "source": str(external / "dedale" / "winlogbeat" / "D02"),
            "load": lambda: _winlogbeat(external / "dedale" / "winlogbeat" / "D02"),
            "path": external / "dedale" / "winlogbeat" / "D02",
            "notes": "DEDALE 2024-12-24. Before the APT begins: no labelled events.",
        },
        {
            "name": "dedale:D03", "group": "dedale", "provenance": EMULATION,
            "source": str(external / "dedale" / "winlogbeat" / "D03"),
            "load": lambda: _winlogbeat(external / "dedale" / "winlogbeat" / "D03"),
            "path": external / "dedale" / "winlogbeat" / "D03",
            "notes": "DEDALE 2024-12-25. Before the APT begins: no labelled events.",
        },
        {
            "name": "dedale:D07", "group": "dedale", "provenance": EMULATION,
            "source": str(external / "dedale" / "winlogbeat" / "D07"),
            "load": lambda: _winlogbeat(external / "dedale" / "winlogbeat" / "D07"),
            "path": external / "dedale" / "winlogbeat" / "D07",
            "notes": "DEDALE 2024-12-29. Before the APT begins: no labelled events.",
        },
        {
            "name": "dedale:D15", "group": "dedale", "provenance": EMULATION,
            "source": str(external / "dedale" / "winlogbeat" / "D15"),
            "load": lambda: _winlogbeat(external / "dedale" / "winlogbeat" / "D15"),
            "path": external / "dedale" / "winlogbeat" / "D15",
            "notes": (
                "DEDALE 2025-01-06: day one of the labelled APT. 434 class-1 events "
                "on CLIENT2 across Sysmon and PowerShell channels."
            ),
        },
        {
            "name": "dedale:D18", "group": "dedale", "provenance": EMULATION,
            "source": str(external / "dedale" / "winlogbeat" / "D18"),
            "load": lambda: _winlogbeat(external / "dedale" / "winlogbeat" / "D18"),
            "path": external / "dedale" / "winlogbeat" / "D18",
            "notes": (
                "DEDALE 2025-01-09: a labelled APT day on CLIENT1 (195 class-1 "
                "Sysmon events), i.e. after lateral movement."
            ),
        },
    ]


# --------------------------------------------------------------------------------------
# The deterministic pipeline, identical to scripts/m19_ablation.py::_pipeline
# --------------------------------------------------------------------------------------


def pipeline(telemetry: Telemetry) -> tuple[list[Any], list[Any], Any]:
    hunt = run_hunt(telemetry, config=HuntConfig())
    environment = build_environment_model(telemetry)
    assessments = assess_findings(hunt.findings, environment)
    cases = correlate(hunt.findings, telemetry, set_aside=set_aside_ids(assessments))
    return list(hunt.findings), list(cases), environment


def row_counts(telemetry: Telemetry) -> dict[str, int]:
    return {
        "process": int(len(telemetry.table(EVENT_PROCESS))),
        "network": int(len(telemetry.table(EVENT_NETWORK))),
        "logon": int(len(telemetry.table(EVENT_LOGON))),
        "control": int(len(telemetry.table(EVENT_CONTROL))),
    }


# --------------------------------------------------------------------------------------
# Ground truth and "has this been tuned against?"
# --------------------------------------------------------------------------------------


def dedale_labels(external: Path) -> dict[str, Any]:
    path = external / "dedale" / "labels" / "dedale_class1_labels.json"
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def dedale_ground_truth(external: Path, day_date: str) -> dict[str, Any]:
    """The labelled stage for one DEDALE day, and which domain its evidence lives in.

    DEDALE's labels name ``host;channel;record_id``. Sysmon 1 and the PowerShell
    channels are process evidence; the label file states outright that no Security
    channel event is labelled, so the *identity* half of any DEDALE chain is unlabelled
    by construction -- a fact this audit must report rather than work around, because a
    cross-domain benchmark built on it could never score the identity side.
    """
    labels = dedale_labels(external)
    scenario = (labels.get("scenarios") or {}).get("apt") or {}
    stage = (scenario.get("stages") or {}).get(day_date)
    if stage is None:
        return {"labelled": False, "note": f"no labelled events on {day_date}"}
    refs = stage.get("refs", [])
    channels = Counter()
    hosts = Counter()
    for ref in refs:
        parts = dict(p.split("=", 1) for p in ref.split(";") if "=" in p)
        channels[parts.get("channel", "")] += 1
        hosts[parts.get("host", "")] += 1
    return {
        "labelled": True,
        "date": day_date,
        "labelled_events": len(refs),
        "hosts": dict(hosts),
        "channels": dict(channels),
        "domains_of_labelled_evidence": ["endpoint"],
        "note": (
            "Every labelled channel is Sysmon or PowerShell, i.e. endpoint evidence. "
            "The label file states that no Security-channel event is labelled, so the "
            "identity stage of this chain has no ground truth."
        ),
        "scenario_note": scenario.get("note", ""),
    }


def synthetic_ground_truth(data_dir: Path) -> dict[str, Any]:
    path = data_dir / "ground_truth.json"
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def git_commits_for(pattern: str, kind: str) -> int:
    """How many commits added or removed a literal (``-S``), or touched a path.

    Used for the held-out question, and it is the only honest answer available: a case
    whose ids and fixtures have been edited across many commits has been iterated
    against in this repository, whatever anybody intended, and cannot be presented as
    held-out evidence in a benchmark.
    """
    args = ["git", "log", "--oneline"]
    args += ["-S", pattern] if kind == "content" else ["--", pattern]
    try:
        out = subprocess.run(
            args, cwd=ROOT, capture_output=True, text=True, check=False, timeout=180,
        )
    except Exception:  # noqa: BLE001
        return -1
    if out.returncode != 0:
        return -1
    return len([line for line in out.stdout.splitlines() if line.strip()])


def tuning_history(spec: dict[str, Any], rule_ids: Iterable[str]) -> dict[str, Any]:
    """Commits that touched a case's inputs: its corpus path and its rules' ids."""
    rules = sorted(set(rule_ids))
    return {
        "commits_touching_source_path": git_commits_for(
            _repo_relative(spec["path"]), "path",
        ),
        "commits_mentioning_rule": {r: git_commits_for(r, "content") for r in rules},
    }


def _repo_relative(path: Path) -> str:
    try:
        return str(Path(path).resolve().relative_to(ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


# --------------------------------------------------------------------------------------
# Running the audit
# --------------------------------------------------------------------------------------


def audit_corpus(
    spec: dict[str, Any], external: Path, limit: int | None = None,
) -> CorpusAudit:
    name = spec["name"]
    path = Path(spec["path"])
    if not path.exists():
        return CorpusAudit(
            name=name, provenance=spec["provenance"], source=spec["source"],
            rows={}, corpus_channels=(), findings=0, cases=0,
            notes=spec["notes"],
            error=f"UNAVAILABLE: {path} does not exist in this checkout",
        )

    started = time.perf_counter()
    try:
        telemetry = spec["load"]()
    except Exception as exc:  # noqa: BLE001 -- a failed load is a reported result
        return CorpusAudit(
            name=name, provenance=spec["provenance"], source=spec["source"],
            rows={}, corpus_channels=(), findings=0, cases=0,
            notes=spec["notes"], error=f"LOAD FAILED: {type(exc).__name__}: {exc}",
        )
    load_seconds = time.perf_counter() - started

    findings, cases, environment = pipeline(telemetry)
    observable = environment.observable_channels
    ground_truth = _corpus_ground_truth(name, external)
    tuning = tuning_history(spec, {f.rule_id for f in findings})

    # attack_data_aws is the one external corpus with a per-case label: the capture
    # file name carries the ATT&CK technique. It is read here rather than left to the
    # corpus-level note, because "which domain does each stage's evidence live in" is a
    # per-case question and answering it corpus-wide would be answering a different one.
    per_case = _capture_labels(telemetry, cases) if name == "attack_data_aws" else {}
    # One pass over the corpus's event ids for all its cases; see event_id_index.
    index = event_id_index(telemetry)

    audits: list[CaseAudit] = []
    for case in cases[: limit or len(cases)]:
        audits.append(audit_case(
            case,
            corpus=name, provenance=spec["provenance"],
            telemetry=telemetry, findings=findings, cases=cases,
            environment=environment, corpus_channels=observable,
            ground_truth={**ground_truth, **per_case.get(case.case_id, {})},
            tuned_against=tuning,
            held_out=False,
            evidence_index=index,
        ))

    notes = spec["notes"] + f" Loaded in {load_seconds:.1f}s."
    return CorpusAudit(
        name=name, provenance=spec["provenance"], source=spec["source"],
        rows=row_counts(telemetry),
        corpus_channels=tuple(sorted(c.value for c in observable)),
        findings=len(findings), cases=len(cases), case_audits=audits, notes=notes,
    )


def _capture_labels(
    telemetry: Telemetry, cases: Sequence[Any],
) -> dict[str, dict[str, Any]]:
    """The attack_data capture label per case, as ``scripts/m19_ablation.py`` derives it.

    The technique is the first ``__``-separated component of the capture file name, and
    the capture is the ``File=`` half of a row's ``source_ref``. A case drawing evidence
    from more than one capture gets no technique rather than an arbitrary one.
    """
    capture_of: dict[str, str] = {}
    for event_type in (EVENT_PROCESS, EVENT_NETWORK, EVENT_LOGON, EVENT_CONTROL):
        frame = telemetry.table(event_type)
        if frame.empty:
            continue
        refs = frame["source_ref"].astype("string").fillna("")
        for event_id, ref in zip(frame["event_id"], refs):
            for part in str(ref).split(";"):
                if part.startswith("File="):
                    capture_of[str(event_id)] = part[len("File="):]

    labels: dict[str, dict[str, Any]] = {}
    for case in cases:
        captures = sorted({capture_of.get(e, "") for e in case.event_ids} - {""})
        labels[case.case_id] = {
            "captures": captures,
            "labelled_technique": (
                captures[0].split("__", 1)[0] if len(captures) == 1 else ""
            ),
            "stage_domains": {"the whole capture": "control_plane"},
        }
    return labels


def _corpus_ground_truth(name: str, external: Path) -> dict[str, Any]:
    if name.startswith("dedale:"):
        day = {
            "dedale:D02": "2024-12-24", "dedale:D03": "2024-12-25",
            "dedale:D07": "2024-12-29", "dedale:D15": "2025-01-06",
            "dedale:D18": "2025-01-09",
        }[name]
        return dedale_ground_truth(external, day)
    if name == "attack_data_aws":
        return {
            "labelled": True,
            "kind": "capture file name carries the ATT&CK technique",
            "domains_of_labelled_evidence": ["control_plane"],
            "note": (
                "Each capture is one technique. Every row the adapter keeps is a "
                "CloudTrail management or authentication event, so the whole labelled "
                "chain lives in one or two channels of one table."
            ),
        }
    if name in {"comiset", "comiset_m17_freeze"}:
        return {
            "labelled": False,
            "note": (
                "COMISET ships no attack labels usable here; M17 recorded it as an "
                "unlabelled real corpus. Any 'chain' is the correlator's, not ground "
                "truth's."
            ),
        }
    if name == "flaws_cloud":
        return {
            "labelled": False,
            "note": (
                "No labels. The published narrative describes levels of a CTF, not "
                "event ids, so no stage of any case can be confirmed."
            ),
        }
    return {"labelled": False, "note": "no attack ground truth for this corpus"}


def audit_synthetic() -> Iterator[CorpusAudit]:
    """The five benchmark incidents in ``ath.evaluation.suite``, each its own corpus."""
    truth = synthetic_ground_truth(ROOT / "data" / "raw")
    for incident in standard_suite(
        ROOT / "data" / "raw",
        ROOT / "tests" / "fixtures" / "cloudtrail",
        ROOT / "tests" / "fixtures" / "k8s_audit",
    ):
        findings, cases, environment = pipeline(incident.telemetry)
        observable = environment.observable_channels
        spec_path = ROOT / "data" / "raw"
        tuning = tuning_history(
            {"path": spec_path}, {f.rule_id for f in findings},
        )
        ground_truth = {
            "labelled": True,
            "incident_id": incident.incident_id,
            "name": incident.name,
            "description": incident.description,
            "malicious_events": len(incident.malicious_event_ids),
            "expected_techniques": sorted(incident.expected_techniques),
            "must_conclude": list(incident.must_conclude),
            "stages": _synthetic_stage_domains(
                truth, incident.incident_id, incident.telemetry,
            ),
        }
        audits = [
            audit_case(
                case,
                corpus=f"synthetic:{incident.incident_id}", provenance=SYNTHETIC,
                telemetry=incident.telemetry, findings=findings, cases=cases,
                environment=environment, corpus_channels=observable,
                ground_truth=ground_truth, tuned_against=tuning, held_out=False,
            )
            for case in cases
        ]
        yield CorpusAudit(
            name=f"synthetic:{incident.incident_id}", provenance=SYNTHETIC,
            source="ath.evaluation.suite",
            rows=row_counts(incident.telemetry),
            corpus_channels=tuple(sorted(c.value for c in observable)),
            findings=len(findings), cases=len(cases), case_audits=audits,
            notes=incident.description,
        )


def _synthetic_stage_domains(
    truth: dict[str, Any], incident_id: str, telemetry: Telemetry,
) -> list[dict[str, Any]]:
    """Each labelled stage of the ground truth, and which domain its evidence lives in.

    ``data/raw/ground_truth.json`` names stages and their ``event_ids``. The event ids
    carry no table prefix (``evt-000357`` could be any of the four), so the domain is
    resolved by looking each id up in the canonical tables -- the only way to say which
    domain a *stage* belongs to rather than guessing from its name.
    """
    if not truth:
        return []
    scenario = {"INC-001": "intrusion", "INC-004": "ransomware_prep"}.get(incident_id)
    if scenario is None:
        return []
    stages = ((truth.get("scenarios") or {}).get(scenario) or {}).get("stages") or {}

    domain_of: dict[str, str] = {}
    for event_type, domain in (
        (EVENT_PROCESS, "endpoint"), (EVENT_NETWORK, "network"),
        (EVENT_LOGON, "identity"), (EVENT_CONTROL, "control_plane"),
    ):
        frame = telemetry.table(event_type)
        if not frame.empty:
            for event_id in frame["event_id"]:
                domain_of[str(event_id)] = domain

    out: list[dict[str, Any]] = []
    for stage, body in stages.items():
        counts: Counter[str] = Counter()
        for event_id in body.get("event_ids", []):
            counts[domain_of.get(str(event_id), "not in this incident's telemetry")] += 1
        out.append({
            "stage": stage,
            "note": body.get("note", ""),
            "evidence_by_domain": dict(counts),
        })
    return out


# --------------------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------------------


def _table(rows: list[list[str]], header: list[str]) -> str:
    lines = ["| " + " | ".join(header) + " |",
             "| " + " | ".join("---" for _ in header) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def render_markdown(payload: dict[str, Any]) -> str:
    corpora = payload["corpora"]
    out: list[str] = []
    out.append("# M19b T4: cross-specialist necessity audit\n")
    out.append(
        f"Generated {payload['generated_at']} at `{payload['head']}`. "
        f"Audit digest `{payload['audit_digest']}`.\n"
    )
    out.append(
        "Every claim in this file is MEASURED unless labelled otherwise: each row was "
        "produced by loading the corpus through the pipeline's own adapters, running "
        "`run_hunt` / `assess_findings` / `correlate` exactly as `scripts/"
        "m19_ablation.py` does, and then running arm A's deterministic investigation "
        "over every case. No rule, threshold or fixture was changed, and no model was "
        "called.\n"
    )

    out.append("## The test, restated\n")
    out.append(
        "A case qualifies only if (1) two or more *domain* specialists "
        "(endpoint / identity / network / control_plane -- the ATT&CK mapper does not "
        "count) have materially relevant evidence, (2) removing either domain removes "
        "a stage rather than a duplicate, and (3) cross-domain synthesis could change "
        "the verdict, the priority or the next action. `docs/m19b-plan.md` fixed this "
        "before any case was looked at.\n"
    )

    out.append("## Summary by corpus\n")
    rows = []
    for corpus in corpora:
        rows.append([
            f"`{corpus['corpus']}`",
            corpus["provenance"].split(" (")[0],
            str(corpus["cases_audited"]),
            str(corpus["qualifying_cases"]),
            str(corpus["cases_with_two_domain_specialists_at_first_step"]),
            ", ".join(corpus["domains_seen"]) or "--",
            corpus["error"] or "loaded",
        ])
    out.append(_table(rows, [
        "corpus", "provenance", "cases", "qualifying",
        "cases offering the planner >=2 domain specialists at step 0",
        "domains present", "load status",
    ]))
    out.append("")

    out.append("## Telemetry each corpus carries at all\n")
    rows = []
    for corpus in corpora:
        counts = corpus["rows"] or {}
        rows.append([
            f"`{corpus['corpus']}`",
            str(counts.get("process", "--")), str(counts.get("network", "--")),
            str(counts.get("logon", "--")), str(counts.get("control", "--")),
            str(corpus["findings"]),
            ", ".join(corpus["corpus_channels"]) or "--",
        ])
    out.append(_table(rows, [
        "corpus", "process rows", "network rows", "logon rows", "control rows",
        "findings", "telemetry channels the corpus has at all",
    ]))
    out.append("")

    out.append("## Every case\n")
    for corpus in corpora:
        out.append(f"### `{corpus['corpus']}`\n")
        out.append(f"*Provenance:* {corpus['provenance']}. *Source:* `{corpus['source']}`.\n")
        out.append(f"{corpus['notes']}\n")
        if corpus["error"]:
            out.append(f"**{corpus['error']}**\n")
            continue
        detail = corpus["cases_detail"]
        if not detail:
            out.append("No case was raised on this corpus.\n")
            continue
        gt = detail[0]["ground_truth"]
        out.append(
            "*Ground truth:* "
            + (json.dumps(gt, default=str) if gt else "none")
            + "\n"
        )
        if len(detail) > 40:
            out.append(
                f"{len(detail)} cases; the per-case table is in `AUDIT.json`. "
                "Distribution:\n"
            )
            out.append(_corpus_distribution(detail))
            out.append("")
            shown = [c for c in detail if c["qualifies"]] or detail[:3]
            out.append("Representative / qualifying cases:\n")
        else:
            shown = detail
        rows = []
        for case in shown:
            rows.append([
                f"`{case['case_id']}`",
                ", ".join(case["rule_ids"]),
                ", ".join(case["domains"]) or "none",
                str(case["independent_evidence_sources"]),
                ", ".join(case["first_step_eligible"]) or "none",
                str(case["first_step_domain_specialists"]),
                str(case["whole_run_specialists_eligible"]),
                "YES" if case["qualifies"] else "no",
                case["failure_reason"] or case["synthesis_statement"],
            ])
        out.append(_table(rows, [
            "case", "rules", "domains with material evidence",
            "independent evidence sources", "eligible at step 0",
            "domain specialists at step 0", "specialists_eligible (whole run)",
            "qualifies", "why",
        ]))
        out.append("")

    out.append(_m19_section(payload))
    out.append(_candidates_section(payload))
    out.append(_near_miss_section(payload))
    out.append(_structural_section(payload))
    out.append(_construction_section(payload))
    out.append(_defects_section(payload))
    out.append(_limitations_section(payload))
    return "\n".join(out)


def _defects_section(payload: dict[str, Any]) -> str:
    """Defects this audit hit while running the pipeline over every corpus.

    Reported, not fixed: this task's brief is to audit, and a worker that repairs the
    code it is measuring has measured its own repair. Each entry names the file and the
    trigger so the fix is a small change for whoever owns it.
    """
    return "\n".join([
        "## Defects this audit surfaced (reported, not fixed)\n",
        f"Running arm A's deterministic investigation over "
        f"{payload['totals']['cases_audited']} cases from {len(payload['corpora'])} "
        "corpora is a wider sweep than the pipeline normally gets. Two things fell out "
        "of it. "
        "Neither is fixed here -- a worker that repairs the code it is measuring has "
        "measured its own repair -- and neither changes a number in this audit.\n",
        "### 1. `NetworkAgent` raises `KeyError: 'robust_cv'` on 3-connection "
        "destinations. MEASURED, VERIFIED FROM CODE.\n",
        "`tests/fixtures/defender_export` triggers it, and `ath.agent.orchestrator.act` "
        "catches it, logs `Specialist network failed`, and the run completes with the "
        "network specialist silently contributing nothing.\n",
        "The cause is an off-by-one between two thresholds that are both spelled `3`:\n",
        "* `ToolBox.analyse_beacon` returns a payload **without** `robust_cv` or "
        "`median_interval_seconds` when `ConnectionPattern.has_measurable_regularity` "
        "is false, which requires `interarrival_count >= 3` -- that is, **four** "
        "connections.\n"
        "* `NetworkAgent.investigate` reaches its irregular-timing branch on "
        "`beacon.get(\"samples\", 0) >= 3` -- that is, **three** connections -- and then "
        "indexes `beacon['robust_cv']` unconditionally.\n",
        "Three connections to one destination therefore satisfy the agent's guard and "
        "not the tool's, and the agent indexes a key the tool did not write. The "
        "narrow fix is to gate that branch on the key the branch reads "
        "(`\"robust_cv\" in beacon`) rather than on a count that only implies it.\n",
        "### 2. `DefenderExportSource` returns no `control` table, and callers index "
        "for one. MEASURED.\n",
        "`load().tables[\"control\"]` raises `KeyError`, so any caller assembling "
        "`Telemetry` from that adapter's tables by subscript fails on a fixture that "
        "loads perfectly well. This script works around it in its own `_telemetry_of` "
        "rather than changing the adapter; the question of whether an adapter should "
        "return an empty frame for a table its source cannot carry belongs to whoever "
        "owns `ath.telemetry`.\n",
    ])


def _m19_section(payload: dict[str, Any]) -> str:
    """Every M19 manifest case, and the one line that says why it fails or qualifies."""
    manifest_path = ROOT / "reports" / "m19" / "ablation" / "MANIFEST.json"
    arm_a_path = ROOT / "reports" / "m19" / "ablation" / "arm_A.json"
    if not manifest_path.is_file():
        return "## The 22 M19 cases\n\nUNAVAILABLE: `reports/m19/ablation/MANIFEST.json` is not in this checkout.\n"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    recorded: dict[tuple[str, str], int] = {}
    if arm_a_path.is_file():
        arm_a = json.loads(arm_a_path.read_text(encoding="utf-8"))
        recorded = {
            (row["corpus"], row["case_id"]):
                row["scores"]["completeness"]["specialists_eligible"]
            for row in arm_a["cases"]
        }

    index = {
        (corpus["corpus"], case["case_id"]): case
        for corpus in payload["corpora"] for case in corpus["cases_detail"]
    }
    rows = []
    qualifying = []
    for entry in manifest["cases"]:
        key = (entry["corpus"], entry["case_id"])
        case = index.get(key)
        if case is None:
            rows.append([f"`{key[0]}` / `{key[1]}`", "--", "--", "NOT AUDITED", "--"])
            continue
        if case["qualifies"]:
            qualifying.append(key)
        arm_value = recorded.get(key)
        agree = (
            "--" if arm_value is None
            else "yes" if arm_value == case["whole_run_specialists_eligible"]
            else f"NO (arm A {arm_value})"
        )
        rows.append([
            f"`{key[0]}` / `{key[1]}`",
            ", ".join(case["domains"]) or "none",
            str(case["first_step_domain_specialists"]),
            "**QUALIFIES**" if case["qualifies"] else case["failure_reason"],
            agree,
        ])

    out = ["## The 22 M19 cases, against the test\n"]
    out.append(
        "The last column is the check `tests/test_m19b_audit.py` runs: this audit's "
        "whole-run eligibility against the `specialists_eligible` arm A recorded in "
        "`reports/m19/ablation/arm_A.json`. Agreement is what makes every other number "
        "here a statement about the pipeline M19 measured.\n"
    )
    out.append(_table(rows, [
        "M19 case", "domains", "domain specialists at step 0",
        "verdict", "agrees with arm A",
    ]))
    out.append("")
    out.append(
        f"**{len(qualifying)} of {len(manifest['cases'])} M19 cases qualify**: "
        + (", ".join(f"`{c}`/`{i}`" for c, i in qualifying) or "none")
        + ". MEASURED.\n"
    )
    return "\n".join(out)


_PROVENANCE_RANK = {
    REAL_LABELLED: 1,
    REAL_UNLABELLED: 2,
    EMULATION: 3,
    REAL_SHAPED: 4,
    REAL_BENIGN: 5,
    SYNTHETIC: 6,
}


def _candidates_section(payload: dict[str, Any]) -> str:
    """Qualifying cases, ranked by provenance: real labelled first, synthetic last."""
    candidates = []
    for corpus in payload["corpora"]:
        for case in corpus["cases_detail"]:
            if case["qualifies"]:
                candidates.append((corpus, case))
    candidates.sort(key=lambda pair: (
        _PROVENANCE_RANK.get(pair[0]["provenance"], 9),
        -pair[1]["independent_evidence_sources"],
        -len(pair[1]["domains"]),
        pair[1]["case_id"],
    ))

    out = ["## Qualifying candidates, ranked by provenance\n"]
    if not candidates:
        out.append(
            "**None.** No case in any corpus this repository can load today passes all "
            "three conditions. MEASURED.\n"
        )
        return "\n".join(out)
    rows = []
    for rank, (corpus, case) in enumerate(candidates, start=1):
        rules = ", ".join(case["rule_ids"])
        tuned = case["tuned_against"].get("commits_mentioning_rule", {})
        rows.append([
            str(rank),
            f"`{corpus['corpus']}` / `{case['case_id']}`",
            corpus["provenance"],
            ", ".join(case["domains"]),
            str(case["independent_evidence_sources"]),
            rules,
            "no -- " + ", ".join(f"{r}: {n} commits" for r, n in sorted(tuned.items())),
        ])
    out.append(_table(rows, [
        "#", "case", "provenance", "domains", "independent sources", "rules",
        "held out?",
    ]))
    out.append("")
    out.append(
        "*Held out* is answered by `git log`: a rule id edited across many commits, or "
        "a fixture rewritten repeatedly, has been iterated against in this repository "
        "whatever anyone intended. On this evidence no existing case can be presented "
        "as held-out data. MEASURED.\n"
    )
    return "\n".join(out)


def _near_miss_section(payload: dict[str, Any]) -> str:
    """Cases that carry two domains and still fail, and precisely where.

    Worth its own section because these are the cases a reader would otherwise assume
    the audit had overlooked, and because each one names a different gap: a rule that
    spans two domains inside one finding, a corpus that has both domains but never in
    one case, a corpus that has the rows and raises no case at all.
    """
    rows = []
    for corpus in payload["corpora"]:
        for case in corpus["cases_detail"]:
            if case["qualifies"] or len(case["domains"]) < 2:
                continue
            rows.append([
                f"`{corpus['corpus']}` / `{case['case_id']}`",
                ", ".join(case["domains"]),
                ", ".join(case["rule_ids"]),
                str(case["first_step_domain_specialists"]),
                case["failure_reason"],
            ])

    out = ["## Near misses: two domains present, still not qualifying\n"]
    if not rows:
        out.append(
            "None. Every non-qualifying case in every corpus carries evidence for at "
            "most one domain -- the failure is never subtle. MEASURED.\n"
        )
    else:
        out.append(_table(rows, [
            "case", "domains", "rules", "domain specialists at step 0", "why it fails",
        ]))
        out.append("")

    # Corpora that carry two domains' worth of telemetry and never put them in one case.
    split = []
    for corpus in payload["corpora"]:
        seen = {tuple(c["domains"]) for c in corpus["cases_detail"]}
        singles = {d[0] for d in seen if len(d) == 1}
        if len(singles) >= 2:
            split.append((corpus, sorted(singles)))
    if split:
        out.append(
            "### Corpora whose cases split cleanly along the domain boundary\n"
        )
        out.append(
            "These corpora carry two domains' worth of telemetry and raise cases in "
            "both -- never in the same case. This is the shape that matters most for "
            "T5, because it is the shape a correlator change (not a data change) "
            "would address:\n"
        )
        out.append(_table([
            [f"`{corpus['corpus']}`", ", ".join(domains),
             str(corpus["cases_audited"]),
             " / ".join(
                 f"{d}: {sum(1 for c in corpus['cases_detail'] if tuple(c['domains']) == (d,))}"
                 for d in domains
             )]
            for corpus, domains in split
        ], ["corpus", "domains raised", "cases", "split"]))
        out.append("")
    return "\n".join(out)


def _structural_section(payload: dict[str, Any]) -> str:
    """Why the corpora look the way they do -- read out of the code, not the data.

    The counts here are the audit's, but the *reason* is structural and checkable in
    two files, which matters: a shortage that follows from the rule catalogue and the
    correlator's link predicates cannot be fixed by fetching more data.
    """
    # Quoted, not imported. These two constants were the correlator's cross-domain
    # allowlist at 41c0d97, the commit this audit measured; the M19b link task deleted
    # them and replaced them with a channel-family predicate. The audit is a statement
    # about the code as it stood, so the values it prints are frozen here rather than
    # read from a module that no longer defines them -- which also keeps
    # `--render-only` able to reproduce `AUDIT.md` byte for byte.
    _AUTH_RULES = frozenset({"ATH-005", "ATH-006"})
    _REMOTE_EXEC_RULES = frozenset({"ATH-007"})
    import ath.hunting.rules  # noqa: F401 -- registers the catalogue
    from ath.environment.coverage import channels_for_fields
    from ath.evaluation.necessity import channel_domains
    from ath.hunting import all_detectors

    by_domains: Counter[tuple[str, ...]] = Counter()
    for detector in all_detectors():
        channels = (
            set(detector.channels) if detector.channels
            else channels_for_fields(detector.fields_used)
        )
        by_domains[tuple(sorted(channel_domains(channels)))] += 1

    rows = [
        [", ".join(domains) or "none", str(count),
         ", ".join(sorted(
             d.rule_id for d in all_detectors()
             if tuple(sorted(channel_domains(
                 set(d.channels) if d.channels else channels_for_fields(d.fields_used)
             ))) == domains
         ))]
        for domains, count in sorted(by_domains.items(), key=lambda kv: -kv[1])
    ]

    out = ["## Why the corpora look like this (VERIFIED FROM CODE)\n"]
    out.append(
        "A case is multi-domain only if its member findings are, and the rule "
        "catalogue decides that before any corpus is loaded:\n"
    )
    out.append(_table(rows, ["domains a rule's findings carry", "rules", "which"]))
    out.append("")
    out.append(
        "Exactly one rule spans two domains on its own (`ATH-003`, endpoint + "
        "network), and it does so *within a single finding* -- which is one stage "
        "described twice, not two stages, so it fails condition 2 by itself.\n"
    )
    out.append(
        "For findings from two different domains to land in one case, "
        "`ath.correlation.correlator.score_pair` must find a **structural** signal "
        "between them. Of its six, four (`shared_evidence`, `same_process`, "
        "`process_lineage`, `sibling_lineage`) require the two findings to cite the "
        "same telemetry event or the same process instance, which two different "
        "canonical tables cannot do across the endpoint/identity/control-plane "
        "boundary except where a rule reads both. `host_movement` needs a directed "
        "host relationship, which no cloud or Kubernetes finding carries. That leaves "
        "`auth_then_exec`, and it is gated by a **hardcoded rule-id allowlist**:\n"
    )
    out.append(
        "```python\n"
        f"_AUTH_RULES = {sorted(_AUTH_RULES)}\n"
        f"_REMOTE_EXEC_RULES = {sorted(_REMOTE_EXEC_RULES)}\n"
        "```\n"
    )
    out.append(
        "So the identity -> endpoint link this project can form at all is exactly "
        "`ATH-005`/`ATH-006` followed by `ATH-007` on the same host inside the "
        "`auth_exec_window`. **No pair of rule ids outside that product can ever "
        "produce a cross-domain case**, whatever the telemetry contains -- an identity "
        "finding and a control-plane finding about the same AWS principal cannot be "
        "correlated by this codebase today. That is the structural reason for every "
        "row in the tables above, and it is the same stale-allowlist failure mode "
        "`ath.agent.specialists.Specialist` documents having removed from the "
        "specialist gates, still in place one layer down. VERIFIED FROM CODE.\n"
    )
    return "\n".join(out)


TARGET_CASES = 8
"""The number of qualifying cases `docs/m19b-plan.md` sizes the T5 benchmark at."""


def _construction_section(payload: dict[str, Any]) -> str:
    """What would have to be built, and what would be synthetic about it.

    Written as a specification for T5 to accept or reject, not as an instruction: this
    task's brief is explicit that nothing here is built. The shapes are constrained by
    the structural section above -- a proposal that assumed a link the correlator
    cannot make would produce cases that never reach the investigation stage.
    """
    qualifying = payload["totals"]["qualifying_cases"]
    shortfall = max(0, TARGET_CASES - qualifying)

    out = ["## If more cases are needed\n"]
    out.append(
        f"**{qualifying} qualifying case(s) exist against a target of about "
        f"{TARGET_CASES}; the shortfall is {shortfall}.** What follows is a "
        "specification for T5, not work done here: nothing below was built, and the "
        "plan forbids adjusting a case after a model has seen it.\n"
    )
    if not shortfall:
        out.append("No additional case is required. MEASURED.\n")
        return "\n".join(out)

    out.append("### The constraint that decides every option\n")
    out.append(
        "Only **one** cross-domain pair can qualify under the code as it stands, and "
        "it is not a matter of which data is fetched:\n\n"
        "* **endpoint x identity** -- reachable. `auth_then_exec` links `ATH-005` or "
        "`ATH-006` to `ATH-007` on one host inside the auth-exec window, and the two "
        "findings are domain-exclusive, so removing either removes a stage. This is "
        "the pair `synthetic:INC-001` already uses.\n"
        "* **endpoint x network** -- unreachable. `ATH-003` is the only rule producing "
        "network channels and it produces process channels from the same finding, so "
        "the network domain can never carry a finding the endpoint domain does not "
        "also read. Condition 2 fails by construction, not by data.\n"
        "* **anything x control_plane** -- unreachable. No structural signal in "
        "`score_pair` can join a `control` row to a `process` or `logon` row, so a "
        "control-plane finding is always alone in its case. This holds for the "
        "Kubernetes route as well: `K8S-001` (the RBAC grant) and `K8S-002` (the "
        "grantee's exec) are **both** `control_plane`, so 'K8s CI plus a grantee exec' "
        "yields one domain, not two, however real the cluster is. VERIFIED FROM CODE.\n"
    )
    out.append(
        "So T5 has two admissible routes, and they are not equivalent:\n\n"
        "**Route A -- build within the architecture.** Construct the shortfall as "
        "endpoint x identity cases. Every one of them is the same shape as INC-001, "
        "which is a real limitation of the resulting benchmark and must be stated in "
        "the pre-registration: it measures whether a crew helps on *one* kind of "
        "cross-domain investigation.\n\n"
        "**Route B -- change the architecture first, then audit again.** A link "
        "predicate joining a cloud authentication finding to a control-plane finding "
        "by *principal and time* (the relationship `flaws_cloud` and the CloudTrail "
        "fixture already contain in their rows and never in their cases) would make "
        "identity x control_plane cases form from **real, unlabelled data** with no "
        "fabrication at all. That is a change to `ath.correlation`, not to a detection "
        "rule, so it is not forbidden by the plan -- but it changes which cases exist, "
        "which means M19's arm A is no longer a baseline for them, and it must be "
        "decided and frozen before any B or C run. HYPOTHESIS: the predicate would "
        "produce cases; how many, and whether they satisfy condition 2, is not known "
        "and this audit does not claim it.\n"
    )

    out.append("### Route A, case by case\n")
    out.append(
        "Each case below is one row of telemetry design. The 'synthetic' column is the "
        "part no data source supplies and this repository would have to write, and it "
        "is the part a reader is entitled to discount.\n"
    )
    out.append(_table([
        [
            "1-3", "endpoint + identity",
            "credential guessing -> successful logon -> service-launched shell on the "
            "target host",
            "real benign background + injected attack",
            "DEDALE D02/D03/D07 benign Winlogbeat hours as background (real bytes, "
            "real hosts, real accounts), with the `ATH-005` burst and the `ATH-007` "
            "service-launched shell written as Winlogbeat records shaped on "
            "`tests/fixtures/real_shaped/dedale/`",
            "the attack rows themselves: the failed-logon burst, the successful logon "
            "and the `services.exe` -> `cmd.exe` pair",
        ],
        [
            "4-5", "endpoint + identity",
            "the same chain across two hosts, so `host_movement` and `auth_then_exec` "
            "both fire and the case spans a boundary",
            "real benign background + injected attack",
            "the same DEDALE background on two hosts",
            "as above, plus the second host's rows",
        ],
        [
            "6-7", "endpoint + identity",
            "a *benign* version of the same shape -- an administrator whose logon "
            "burst is a mistyped password and whose shell is patch management",
            "real benign background + injected benign look-alike",
            "DEDALE benign hours; the look-alike is modelled on the "
            "`benign_lookalike` scenario already in `data/raw/ground_truth.json`",
            "the look-alike rows. These are the cases that make the benchmark "
            "discriminative rather than a recall test, and without them a crew that "
            "always says 'intrusion' scores perfectly",
        ],
        [
            "8", "endpoint + identity",
            "held out: generated by the same committed code under a seed that is not "
            "read until final evaluation",
            "real benign background + injected attack",
            "as 1-3",
            "as 1-3; what makes it held out is the seal, not the construction",
        ],
    ], [
        "case(s)", "domains", "chain", "provenance it would carry",
        "most realistic construction route available", "what would be synthetic",
    ]))
    out.append("")
    dedale = {
        corpus["corpus"]: corpus for corpus in payload["corpora"]
        if corpus["corpus"].startswith("dedale:")
    }
    dedale_measured = "; ".join(
        f"{name} {corpus['findings']} findings / {corpus['cases']} cases"
        + (f" [{corpus['error'][:40]}]" if corpus["error"] else "")
        for name, corpus in sorted(dedale.items())
    ) or "not audited in this run"

    out.append("### Routes this audit examined and rejected\n")
    out.append(_table([
        [
            "DEDALE D15-D22 attack days",
            "**The premise is wrong: D15 and D18 were fetched and are on disk.** D15 "
            "(2025-01-06, 434 labelled events) and D18 (2025-01-09, 195) are the "
            "first and fourth labelled APT days. Measured at this HEAD: "
            f"{dedale_measured}. "
            "`reports/m14/dedale_d15.json` recorded 30 findings, all `ATH-004` and all "
            "CRITICAL, on identical row counts -- and M16-1 established those were "
            "false positives from argv[0] guessing, fixed in `626e037`. The 30 "
            "findings were the defect; their absence is the fix. HYPOTHESIS: fetching "
            "D16-D22 would not change this, because the rules that would have to fire "
            "read command lines and lineage this export does not carry in a shape "
            "they match -- untested, and testable by fetching one more day. "
            "Separately, DEDALE's labels cover Sysmon and PowerShell only -- the label "
            "file says so outright -- so the identity half of any DEDALE chain could "
            "not be scored even if a case formed.",
        ],
        [
            "flaws.cloud actors that both authenticate and mutate IAM",
            "The corpus does carry both: 79,424 authentication rows and 1,857,154 "
            "control rows, and it raises cases in both domains. It raises **no case "
            "containing both**, and cannot, because no structural signal joins a "
            "`logon` finding to a `control` finding. This is Route B's territory, not "
            "a data-collection task.",
        ],
        [
            "K8s CI plus a grantee exec",
            "Both halves are `control_plane`. `INC-005` already builds exactly this "
            "chain and the audit scores it one domain. Real cluster data would not "
            "change the domain count.",
        ],
        [
            "`tests/fixtures/defender_export`",
            "The only fixture in the repository carrying process, network and logon "
            "rows at once, and its single case still fails condition 2 -- the network "
            "half is `ATH-003`, which the endpoint specialist reads too.",
        ],
    ], ["route", "why it does not yield a qualifying case"]))
    out.append("")
    return "\n".join(out)


def _limitations_section(payload: dict[str, Any]) -> str:
    out = ["## Limitations of this audit\n"]
    out.append(
        "* **Condition 3 is a rule, not a judgement.** `_synthesis_statement` derives "
        "its answer from conditions 1 and 2 rather than reasoning about each case, so "
        "it can neither rescue a case the first two conditions reject nor reject one "
        "they accept. On this corpus the question never arises -- one case passes the "
        "first two conditions -- but on a richer corpus condition 3 would need a human "
        "reading rather than this function.\n"
        "* **Condition 2 is strict about a finding that spans two domains.** A single "
        "finding relevant to two specialists counts as one stage. `ATH-003` is the "
        "only rule this affects, and the choice is stated rather than hidden: a "
        "looser reading would qualify any case containing `ATH-003`, and the planner "
        "would still be choosing between two specialists reading the same rows.\n"
        "* **Domain membership is computed from `fields_used`, so it can over-count.** "
        "`ATH-003` reads only the network table yet declares `process_name` and "
        "`process_id`, which map to the process-execution channel -- so the endpoint "
        "specialist is eligible on a case built from network rows alone. That is the "
        "pipeline's own behaviour, reported as measured, not an artefact of this "
        "script.\n"
        "* **'Held out' is answered by `git log`, which is a lower bound.** A rule "
        "tuned by editing a threshold in a file the rule id does not appear in is not "
        "counted.\n"
        "* **Unlabelled corpora cannot be scored on condition 1's 'belongs to the "
        "labelled attack chain' clause.** For `flaws_cloud` and `comiset` the audit "
        "falls back to the plan's second clause -- the same actor/host/time story the "
        "case's findings tell -- which the correlator has already enforced by "
        "construction.\n"
        "* **No model was called and no rule was changed**, so nothing here is a "
        "statement about detection quality.\n"
    )
    return "\n".join(out)


def _corpus_distribution(detail: list[dict[str, Any]]) -> str:
    by_domains = Counter(tuple(c["domains"]) for c in detail)
    by_first = Counter(c["first_step_domain_specialists"] for c in detail)
    by_eligible = Counter(c["whole_run_specialists_eligible"] for c in detail)
    lines = ["", "```"]
    lines.append("domains with material evidence:")
    for domains, n in by_domains.most_common():
        lines.append(f"  {', '.join(domains) or 'none':40s} {n:5d} cases")
    lines.append("domain specialists eligible at step 0:")
    for k, n in sorted(by_first.items()):
        lines.append(f"  {k:40d} {n:5d} cases")
    lines.append("specialists_eligible over the whole run (arm A's number):")
    for k, n in sorted(by_eligible.items()):
        lines.append(f"  {k:40d} {n:5d} cases")
    lines.append("```")
    return "\n".join(lines)


def head() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:  # noqa: BLE001
        return "unknown"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--external", type=Path, default=DEFAULT_EXTERNAL)
    parser.add_argument(
        "--corpora", choices=("all", "fast", "dedale"), default="all",
        help="'fast' skips the multi-hundred-megabyte DEDALE slices.",
    )
    parser.add_argument("--out", type=Path, default=OUT_DIR)
    parser.add_argument(
        "--limit-cases", type=int, default=None,
        help="Audit at most N cases per corpus. Development only; the committed run "
             "uses every case.",
    )
    parser.add_argument(
        "--render-only", action="store_true",
        help="Re-render AUDIT.md from an existing AUDIT.json without re-auditing. The "
             "measurements are in the JSON; this exists so the prose can be corrected "
             "without a twenty-minute re-run silently changing a number beside it.",
    )
    args = parser.parse_args()

    if args.render_only:
        payload = json.loads((args.out / "AUDIT.json").read_text(encoding="utf-8"))
        (args.out / "AUDIT.md").write_text(render_markdown(payload), encoding="utf-8")
        print(f"re-rendered {args.out / 'AUDIT.md'} from AUDIT.json (no corpus loaded).")
        return 0

    specs = corpus_specs(args.external.resolve())
    if args.corpora != "all":
        specs = [s for s in specs if s["group"] == args.corpora]

    corpora: list[CorpusAudit] = []
    for spec in specs:
        started = time.perf_counter()
        print(f"auditing {spec['name']} ...", flush=True)
        corpus = audit_corpus(spec, args.external.resolve(), args.limit_cases)
        corpora.append(corpus)
        print(
            f"  {corpus.cases} cases, {len(corpus.qualifying)} qualifying, "
            f"{time.perf_counter() - started:.1f}s"
            + (f" [{corpus.error}]" if corpus.error else ""),
            flush=True,
        )

    if args.corpora in ("all", "fast"):
        for corpus in audit_synthetic():
            corpora.append(corpus)
            print(
                f"auditing {corpus.name} ... {corpus.cases} cases, "
                f"{len(corpus.qualifying)} qualifying", flush=True,
            )

    body = [c.to_dict() for c in corpora]
    payload: dict[str, Any] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "head": head(),
        "task": "M19b T4 cross-specialist necessity audit",
        "necessity_test": {
            "1": "two or more domain specialists have materially relevant evidence",
            "2": "removing a domain removes a stage, not a duplicate",
            "3": "cross-domain synthesis could change verdict, priority or next action",
            "note": "the ATT&CK mapper is not a domain specialist",
        },
        "corpora": body,
    }
    payload["totals"] = {
        "corpora_audited": len([c for c in corpora if not c.error]),
        "corpora_unavailable": [c.name for c in corpora if c.error],
        "cases_audited": sum(len(c.case_audits) for c in corpora),
        "qualifying_cases": sum(len(c.qualifying) for c in corpora),
        "qualifying": [
            {"corpus": c.name, "case_id": a.case_id, "provenance": c.provenance}
            for c in corpora for a in c.qualifying
        ],
    }
    payload["audit_digest"] = audit_digest(body)

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "AUDIT.json").write_text(
        json.dumps(payload, indent=2, default=str), encoding="utf-8",
    )
    (args.out / "AUDIT.md").write_text(render_markdown(payload), encoding="utf-8")
    print(
        f"\n{payload['totals']['cases_audited']} cases audited, "
        f"{payload['totals']['qualifying_cases']} qualifying. "
        f"Wrote {args.out / 'AUDIT.json'} and {args.out / 'AUDIT.md'}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
